#!/bin/bash

# Put your code here
# You may only use the following external programs: ls, echo, awk, cat, grep, sort, wc, bc
file='input.txt'
keywords=()
IFS=" "
score=()
keyword=()
n=0
string=""
liner=$(awk -F '[[:space:]]+' '{for(i=1;i<=NF;i++){printf "%s ", $i}; printf "\n"}' $file)
arr=( $liner )

while read -r line ; do 
IFS=' ' read -r -a array <<< "$line"
string=""
for item in "${array[@]}"; do
	if [[ $item =~ [0-9] ]]; then
	continue
	else
	string="$string $item"
	fi
done
n=$(( n + 1 ))
string=${string## }
keyword[$n]=${string}

lastfield=${#array[@]}
score[$n]=${array[$((lastfield - 1))]}

done <<< $liner

declare -A pair
count=0
cd submissions
for resume in *; do
	count=0
	for (( i=1; i<${#keyword[@]}+1; i++ )); do
		
		var=$(grep -o -i "${keyword[$i]}" "$resume" | wc -l)
		num=${score[$i]}
		val=$(awk -v var="${var}" -v num="${num}" 'BEGIN{print (var*num)}')
		count=$(awk -v count="${count}" -v val="${val}" 'BEGIN{print (count+val)}')
	done
	pair["$resume"]=$count
done
rev=()

for key in "${!pair[@]}"
do
	printf '%s %s\n' "${pair[$key]}" "$key"
done | sort -rn -k1
